using Homm3.WPF.Model;
using System.Collections.Generic;
using System.Linq;

namespace Homm3.WPF
{
	public static class MapObjectFactory
	{
		private static readonly List<MapObject> mapObjects;

		static MapObjectFactory()
		{
			mapObjects = new List<MapObject>();

			mapObjects.Add(new MapObject("", 0));
			mapObjects.AddRange(ListAdventureMapObjects());
			mapObjects.AddRange(ListArtifacts());
			mapObjects.AddRange(ListDwellings());

			var unknownMapObjects = ListUnknownMapObjects(mapObjects);
			mapObjects.AddRange(unknownMapObjects);
			mapObjects.Sort();
		}

		public static List<MapObject> CreateMapObjects()
		{
			return mapObjects.ToList();
		}

		private static IEnumerable<UnknownMapObject> ListUnknownMapObjects(IEnumerable<MapObject> existingMapObjects)
		{
			yield return new UnknownMapObject("Pandora's Box (GUESS)", "Pandora's Box", "(Boxes with monsters are not included in the guess)", existingMapObjects.OfType<GuessableMapObject>().Where(mo => mo.Name.StartsWith("Pandora's Box ")));
			yield return new UnknownMapObject("Prison (GUESS)", "Prison", "", existingMapObjects.OfType<GuessableMapObject>().Where(mo => mo.Name.StartsWith("Prison ")));
			yield return new UnknownMapObject("Spell Scroll (GUESS)", "Spell Scroll", "", existingMapObjects.OfType<GuessableMapObject>().Where(mo => mo.Name.StartsWith("Spell Scroll ")));
		}

		private static IEnumerable<MapObject> ListAdventureMapObjects()
		{
			yield return new MapObject("Alchemist's Lab", 3500);
			yield return new MapObject("Altar of Mana", 100);
			yield return new MapObject("Altar of Sacrifice", 100);
			yield return new MapObject("Ancient Lamp", 5000);
			yield return new MapObject("Arena", 3000);
			yield return new MapObject("Beholders' Sanctuary", 2500);
			yield return new MapObject("Black Market", 8000);
			yield return new MapObject("Black Tower", 1500);
			yield return new MapObject("Buoy", 100);
			yield return new MapObject("Campfire", 2000);
			yield return new MapObject("Cannon Yard", 3000);
			yield return new MapObject("Cartographer (Ground)", 10000);
			yield return new MapObject("Cartographer (Underground)", 7500);
			yield return new MapObject("Cartographer (Water)", 5000);
			yield return new MapObject("Churchyard", 1500);
			yield return new MapObject("Colosseum of the Magi", 3000);
			yield return new MapObject("Corpse", 500);
			yield return new MapObject("Cover of Darkness", 500);
			yield return new MapObject("Crypt", 1000);
			yield return new MapObject("Crystal", 2000);
			yield return new MapObject("Crystal Cavern", 3500);
			yield return new MapObject("Cyclops Stockpile", 3000);
			yield return new MapObject("Den of Thieves", 100);
			yield return new MapObject("Derelict Ship", 4000);
			yield return new MapObject("Derrick", 750);
			yield return new MapObject("Dragon Fly Hive", 9000);
			yield return new MapObject("Dragon Utopia", 10000);
			yield return new MapObject("Dwarven Treasury", 2000);
			yield return new MapObject("Experimental Shop", 3500);
			yield return new MapObject("Eye of the Magi", 100);
			yield return new MapObject("Faerie Ring", 100);
			yield return new MapObject("Flotsam", 500);
			yield return new MapObject("Fountain of Fortune", 100);
			yield return new MapObject("Fountain of Youth", 100);
			yield return new MapObject("Freelancer's Guild", 100);
			yield return new MapObject("Garden of Revelation", 1500);
			yield return new MapObject("Gazebo", 1500);
			yield return new MapObject("Gems", 2000);
			yield return new MapObject("Gem Pond", 3500);
			yield return new MapObject("Gold", 750);
			yield return new MapObject("Gold Mine", 7000);
			yield return new MapObject("Grave", 500);
			yield return new MapObject("Griffin Conservatory", 2000);
			yield return new MapObject("Hermit's Shack", 1500);
			yield return new MapObject("Hill Fort (Old or New)", 7000);
			yield return new MapObject("Hut of the Magi", 100);
			yield return new MapObject("Idol of Fortune", 100);
			yield return new MapObject("Imp Cache", 5000);
			yield return new MapObject("Ivory Tower", 7000);
			yield return new MapObject("Jetsam", 500);
			yield return new MapObject("Junkman", 200);
			yield return new MapObject("Lean To", 500);
			yield return new MapObject("Learning Stone", 1500);
			yield return new MapObject("Library of Enlightenment", 12000);
			yield return new MapObject("Magic Spring", 500);
			yield return new MapObject("Magic Well", 250);
			yield return new MapObject("Major Artifact", 10000);
			yield return new MapObject("Mansion", 5000);
			yield return new MapObject("Marletto Tower", 1500);
			yield return new MapObject("Medusa Stores", 1500);
			yield return new MapObject("Mercenary Camp", 1500);
			yield return new MapObject("Mercury", 2000);
			yield return new MapObject("Mermaids", 100);
			yield return new MapObject("Mineral Spring", 500);
			yield return new MapObject("Minor Artifact", 5000);
			yield return new MapObject("Mystical Garden", 500);
			yield return new MapObject("Naga Bank", 3000);
			yield return new MapObject("Oasis", 100);
			yield return new MapObject("Obelisk", 350);
			yield return new MapObject("Observatory", 500);
			yield return new MapObject("Observation Tower", 750);
			yield return new MapObject("Ore", 1400);
			yield return new MapObject("Ore Pit", 1500);
			yield return new GuessableMapObject("Pandora's Box (5k exp)", 6000, "Pandora's Box exp 05k", "exp", "5k");
			yield return new GuessableMapObject("Pandora's Box (10k exp)", 12000, "Pandora's Box exp 10k", "exp", "10k");
			yield return new GuessableMapObject("Pandora's Box (15k exp)", 18000, "Pandora's Box exp 15k", "exp", "15k");
			yield return new GuessableMapObject("Pandora's Box (20k exp)", 24000, "Pandora's Box exp 20k", "exp", "20k");
			yield return new GuessableMapObject("Pandora's Box (5k gold)", 5000, "Pandora's Box gold 05k", "gold", "5k");
			yield return new GuessableMapObject("Pandora's Box (10k gold)", 10000, "Pandora's Box gold 10k", "gold", "10k");
			yield return new GuessableMapObject("Pandora's Box (15k gold)", 15000, "Pandora's Box gold 15k", "gold", "15k");
			yield return new GuessableMapObject("Pandora's Box (20k gold)", 20000, "Pandora's Box gold 20k", "gold", "20k");
			yield return new GuessableMapObject("Pandora's Box (1st lvl spells)", 5000, "Pandora's Box spell 1", "spell", "lvl 1");
			yield return new GuessableMapObject("Pandora's Box (2nd lvl spells)", 7500, "Pandora's Box spell 2", "spell", "lvl 2");
			yield return new GuessableMapObject("Pandora's Box (3rd lvl spells)", 10000, "Pandora's Box spell 3", "spell", "lvl 3");
			yield return new GuessableMapObject("Pandora's Box (4th lvl spells)", 12500, "Pandora's Box spell 4", "spell", "lvl 4");
			yield return new GuessableMapObject("Pandora's Box (5th lvl spells)", 15000, "Pandora's Box spell 5", "spell", "lvl 5");
			yield return new GuessableMapObject("Pandora's Box (all air spells)", 15000, "Pandora's Box spell all air", "spell", "air");
			yield return new GuessableMapObject("Pandora's Box (all earth spells)", 15000, "Pandora's Box spell all earth", "spell", "earth");
			yield return new GuessableMapObject("Pandora's Box (all fire spells)", 15000, "Pandora's Box spell all fire", "spell", "fire");
			yield return new GuessableMapObject("Pandora's Box (all water spells)", 15000, "Pandora's Box spell all water", "spell", "water");
			yield return new GuessableMapObject("Pandora's Box (all spells)", 30000, "Pandora's Box spell full all", "spell", "all");
			yield return new MapObject("Pandora's Box (lvl 1 monster)", 5000, "Pandora's Box monster 1");
			yield return new MapObject("Pandora's Box (lvl 2 monster)", 7000, "Pandora's Box monster 2");
			yield return new MapObject("Pandora's Box (lvl 3 monster)", 9000, "Pandora's Box monster 3");
			yield return new MapObject("Pandora's Box (lvl 4 monster)", 12000, "Pandora's Box monster 4");
			yield return new MapObject("Pandora's Box (lvl 5 monster)", 16000, "Pandora's Box monster 5");
			yield return new MapObject("Pandora's Box (lvl 6 monster)", 21000, "Pandora's Box monster 6");
			yield return new MapObject("Pandora's Box (lvl 7 monster)", 27000, "Pandora's Box monster 7");
			yield return new MapObject("Pillar of Fire", 750);
			yield return new MapObject("Pirate Cavern", 3500);
			yield return new GuessableMapObject("Prison (lvl 1 hero)", 2500, "Prison 01", "", "lvl 1");
			yield return new GuessableMapObject("Prison (lvl 5 hero)", 5000, "Prison 05", "", "lvl 5");
			yield return new GuessableMapObject("Prison (lvl 10 hero)", 10000, "Prison 10", "", "lvl 10");
			yield return new GuessableMapObject("Prison (lvl 20 hero)", 20000, "Prison 20", "", "lvl 20");
			yield return new GuessableMapObject("Prison (lvl 30 hero)", 30000, "Prison 30", "", "lvl 30");
			yield return new MapObject("Prospector", 500);
			yield return new MapObject("Pyramid", 5000);
			yield return new MapObject("Rally Flag", 100);
			yield return new MapObject("Random Resource", 1500);
			yield return new MapObject("Redwood Observatory", 750);
			yield return new MapObject("Red Tower", 4000);
			yield return new MapObject("Refugee Camp", 5000);
			yield return new MapObject("Relic Artifact", 20000);
			yield return new MapObject("Ruins", 1000);
			yield return new MapObject("Sanctuary", 100);
			yield return new MapObject("Sawmill", 1500);
			yield return new MapObject("Scholar", 1500);
			yield return new MapObject("School of Magic", 1000);
			yield return new MapObject("School of War", 1000);
			yield return new MapObject("Sea Barrel", 500);
			yield return new MapObject("Sea Chest", 1500);
			yield return new MapObject("Seafaring Academy", 8000);
			yield return new GuessableMapObject("Seer's Hut (5k exp)", 2000, "Seer's Hut exp 05", "exp", "5k");
			yield return new GuessableMapObject("Seer's Hut (10k exp)", 5333, "Seer's Hut exp 10", "exp", "10k");
			yield return new GuessableMapObject("Seer's Hut (15k exp)", 8666, "Seer's Hut exp 15", "exp", "15k");
			yield return new GuessableMapObject("Seer's Hut (20k exp)", 12000, "Seer's Hut exp 20", "exp", "20k");
			yield return new GuessableMapObject("Seer's Hut (5k gold)", 2000, "Seer's Hut gold 05", "gold", "5k");
			yield return new GuessableMapObject("Seer's Hut (10k gold)", 5333, "Seer's Hut gold 10", "gold", "10k");
			yield return new GuessableMapObject("Seer's Hut (15k gold)", 8666, "Seer's Hut gold 15", "gold", "15k");
			yield return new GuessableMapObject("Seer's Hut (20k gold)", 12000, "Seer's Hut gold 20", "gold", "20k");
			yield return new MapObject("Seer's Box (lvl 1 monster)", 5000, "Seer's Box monster 1");
			yield return new MapObject("Seer's Box (lvl 2 monster)", 7000, "Seer's Box monster 2");
			yield return new MapObject("Seer's Box (lvl 3 monster)", 9000, "Seer's Box monster 3");
			yield return new MapObject("Seer's Box (lvl 4 monster)", 12000, "Seer's Box monster 4");
			yield return new MapObject("Seer's Box (lvl 5 monster)", 16000, "Seer's Box monster 5");
			yield return new MapObject("Seer's Box (lvl 6 monster)", 21000, "Seer's Box monster 6");
			yield return new MapObject("Seer's Box (lvl 7 monster)", 27000, "Seer's Box monster 7");
			yield return new MapObject("Shipwreck Survivor", 1500);
			yield return new MapObject("Shipwreck", 2000);
			yield return new MapObject("Shrine of Magic Gesture (2nd lvl spell)", 2000, "Shrine of Magic 2");
			yield return new MapObject("Shrine of Magic Incantation (1st lvl spell)", 500, "Shrine of Magic 1");
			yield return new MapObject("Shrine of Magic Mystery (4th lvl spell)", 7000, "Shrine of Magic 4");
			yield return new MapObject("Shrine of Magic Thought (3rd lvl spell)", 3000, "Shrine of Magic 3");
			yield return new MapObject("Skeleton Transformer", 500);
			yield return new GuessableMapObject("Spell Scroll lvl 1", 500, "Spell Scroll lvl 1", "", "lvl 1");
			yield return new GuessableMapObject("Spell Scroll lvl 2", 2000, "Spell Scroll lvl 2", "", "lvl 2");
			yield return new GuessableMapObject("Spell Scroll lvl 3", 3000, "Spell Scroll lvl 3", "", "lvl 3");
			yield return new GuessableMapObject("Spell Scroll lvl 4 (exc. TP and Water Walk)", 8000, "Spell Scroll lvl 4", "", "lvl 4");
			yield return new GuessableMapObject("Spell Scroll lvl 5 (exc. DD and Fly)", 10000, "Spell Scroll lvl 5", "", "lvl 5");
			yield return new GuessableMapObject("Spell Scroll (TP, Water Walk, DD or Fly)", 20000, "Spell Scroll lvl air", "", "air control");
			yield return new MapObject("Spit", 1500);
			yield return new MapObject("Stables", 200);
			yield return new MapObject("Star Axis", 1500);
			yield return new MapObject("Sulfur", 2000);
			yield return new MapObject("Sulfur Dune", 3500);
			yield return new MapObject("Swan Pond", 100);
			yield return new MapObject("Tavern", 100);
			yield return new MapObject("Temple of Loyalty", 100);
			yield return new MapObject("Temple of the Sea", 10000);
			yield return new MapObject("Temple", 100);
			yield return new MapObject("Town Gate", 10000);
			yield return new MapObject("Trading Post", 3000);
			yield return new MapObject("Trailblazer", 200);
			yield return new MapObject("Treasure Artifact", 2000);
			yield return new MapObject("Treasure Chest", 1500);
			yield return new MapObject("Tree of Knowledge", 2500);
			yield return new MapObject("University", 2500);
			yield return new MapObject("Vial of Mana", 3000);
			yield return new MapObject("Wagon", 500);
			yield return new MapObject("War Machine Factory", 1500);
			yield return new MapObject("Warehouse (Crystal)", 2500);
			yield return new MapObject("Warehouse (Gems)", 2500);
			yield return new MapObject("Warehouse (Gold)", 6000);
			yield return new MapObject("Warehouse (Mercury)", 2500);
			yield return new MapObject("Warehouse (Ore)", 2250);
			yield return new MapObject("Warehouse (Sulfur)", 2500);
			yield return new MapObject("Warehouse (Wood)", 2250);
			yield return new MapObject("Warlock's Lab", 3000);
			yield return new MapObject("Warrior's Tomb", 6000);
			yield return new MapObject("Water Wheel", 750);
			yield return new MapObject("Watering Hole", 500);
			yield return new MapObject("Watering Place", 500);
			yield return new MapObject("Windmill", 2500);
			yield return new MapObject("Witch Hut", 1500);
			yield return new MapObject("Wolf Raider Picket", 9500);
			yield return new MapObject("Wood", 1400);
		}

		private static IEnumerable<MapObject> ListArtifacts()
		{
			yield return new MapObject("Amulet of the Undertaker", 2000);
			yield return new MapObject("Badge of Courage", 2000);
			yield return new MapObject("Bird of Perception", 2000);
			yield return new MapObject("Bow of Elven Cherrywood", 2000);
			yield return new MapObject("Breastplate of Petrified Wood", 2000);
			yield return new MapObject("Cape of Conjuring", 2000);
			yield return new MapObject("Cards of Prophecy", 2000);
			yield return new MapObject("Centaur's Axe", 2000);
			yield return new MapObject("Charm of Mana", 2000);
			yield return new MapObject("Clover of Fortune", 2000);
			yield return new MapObject("Collar of Conjuring", 2000);
			yield return new MapObject("Crest of Valor", 2000);
			yield return new MapObject("Dragonbone Greaves", 2000);
			yield return new MapObject("Glyph of Gallantry", 2000);
			yield return new MapObject("Helm of the Alabaster Unicorn", 2000);
			yield return new MapObject("Hourglass of the Evil Hour", 2000);
			yield return new MapObject("Ladybird of Luck", 2000);
			yield return new MapObject("Legs of Legion", 2000);
			yield return new MapObject("Mystic Orb of Mana", 2000);
			yield return new MapObject("Necklace of Swiftness", 2000);
			yield return new MapObject("Pendant of Death", 2000);
			yield return new MapObject("Pendant of Dispassion", 2000);
			yield return new MapObject("Pendant of Free Will", 2000);
			yield return new MapObject("Pendant of Holiness", 2000);
			yield return new MapObject("Pendant of Life", 2000);
			yield return new MapObject("Pendant of Total Recall", 2000);
			yield return new MapObject("Quiet Eye of the Dragon", 2000);
			yield return new MapObject("Ring of Conjuring", 2000);
			yield return new MapObject("Ring of Vitality", 2000);
			yield return new MapObject("Shield of the Dwarven Lords", 2000);
			yield return new MapObject("Skull Helmet", 2000);
			yield return new MapObject("Speculum", 2000);
			yield return new MapObject("Spirit of Oppression", 2000);
			yield return new MapObject("Spyglass", 2000);
			yield return new MapObject("Still Eye of the Dragon", 2000);
			yield return new MapObject("Stoic Watchman", 2000);
			yield return new MapObject("Talisman of Mana", 2000);
			yield return new MapObject("Demon's Horseshoe", 2000);
			yield return new MapObject("Ring of Suppression", 2000);
			yield return new MapObject("Runes of Imminency", 2000);

			yield return new MapObject("Armor of Wonder", 5000);
			yield return new MapObject("Blackshard of the Dead Knight", 5000);
			yield return new MapObject("Boots of Speed", 5000);
			yield return new MapObject("Bowstring of the Unicorn's Mane", 5000);
			yield return new MapObject("Buckler of the Gnoll King", 5000);
			yield return new MapObject("Crown of the Supreme Magi", 5000);
			yield return new MapObject("Dragon Wing Tabard", 5000);
			yield return new MapObject("Emblem of Cognizance", 5000);
			yield return new MapObject("Equestrian's Gloves", 5000);
			yield return new MapObject("Greater Gnoll's Flail", 5000);
			yield return new MapObject("Helm of Chaos", 5000);
			yield return new MapObject("Inexhaustible Cart of Ore", 5000);
			yield return new MapObject("Inexhaustible Cart of Lumber", 5000);
			yield return new MapObject("Loins of Legion", 5000);
			yield return new MapObject("Red Dragon Flame Tongue", 5000);
			yield return new MapObject("Rib Cage", 5000);
			yield return new MapObject("Ring of Life", 5000);
			yield return new MapObject("Scales of the Greater Basilisk", 5000);
			yield return new MapObject("Shield of the Yawning Dead", 5000);
			yield return new MapObject("Torso of Legion", 5000);
			yield return new MapObject("Vampire's Cowl", 5000);
			yield return new MapObject("Hideous Mask", 5000);
			yield return new MapObject("Shaman's Puppet", 5000);

			yield return new MapObject("Ambassador's Sash", 10000);
			yield return new MapObject("Angel Feather Arrows", 10000);
			yield return new MapObject("Arms of Legion", 10000);
			yield return new MapObject("Breastplate of Brimstone", 10000);
			yield return new MapObject("Cape of Velocity", 10000);
			yield return new MapObject("Dead Man's Boots", 10000);
			yield return new MapObject("Diplomat's Ring", 10000);
			yield return new MapObject("Dragon Scale Shield", 10000);
			yield return new MapObject("Endless Bag of Gold", 10000);
			yield return new MapObject("Endless Purse of Gold", 10000);
			yield return new MapObject("Everflowing Crystal Cloak", 10000);
			yield return new MapObject("Everpouring Vial of Mercury", 10000);
			yield return new MapObject("Eversmoking Ring of Sulfur", 10000);
			yield return new MapObject("Garniture of Interference", 10000);
			yield return new MapObject("Golden Bow", 10000);
			yield return new MapObject("Head of Legion", 10000);
			yield return new MapObject("Hellstorm Helmet", 10000);
			yield return new MapObject("Necklace of Dragonteeth", 10000);
			yield return new MapObject("Necklace of Ocean Guidance", 10000);
			yield return new MapObject("Ogre's Club of Havoc", 10000);
			yield return new MapObject("Orb of Driving Rain", 10000);
			yield return new MapObject("Orb of the Firmament", 10000);
			yield return new MapObject("Orb of Silt", 10000);
			yield return new MapObject("Orb of Tempestuous Fire", 10000);
			yield return new MapObject("Pendant of Courage", 10000);
			yield return new MapObject("Pendant of Negativity", 10000);
			yield return new MapObject("Pendant of Second Sight", 10000);
			yield return new MapObject("Recanter's Cloak", 10000);
			yield return new MapObject("Ring of Infinite Gems", 10000);
			yield return new MapObject("Ring of the Wayfarer", 10000);
			yield return new MapObject("Shackles of War", 10000);
			yield return new MapObject("Shield of the Damned", 10000);
			yield return new MapObject("Sphere of Permanence", 10000);
			yield return new MapObject("Statesman's Medal", 10000);
			yield return new MapObject("Surcoat of Counterpoise", 10000);
			yield return new MapObject("Sword of Hellfire", 10000);
			yield return new MapObject("Targ of the Rampaging Ogre", 10000);
			yield return new MapObject("Tunic of the Cyclops King", 10000);
			yield return new MapObject("Vial of Lifeblood", 10000);
			yield return new MapObject("Cape of Silence", 10000);
			yield return new MapObject("Crown of the Five Seas", 10000);
			yield return new MapObject("Pendant of Downfall", 10000);
			yield return new MapObject("Ring of Oblivion", 10000);
			yield return new MapObject("Royal Armor of Nix", 10000);
			yield return new MapObject("Shield of Naval Glory", 10000);
			yield return new MapObject("Trident of Dominion", 10000);
			yield return new MapObject("Wayfarer's Boots", 10000);

			yield return new MapObject("Angel Wings", 20000);
			yield return new MapObject("Armageddon's Blade", 20000);
			yield return new MapObject("Boots of Levitation", 20000);
			yield return new MapObject("Boots of Polarity", 20000);
			yield return new MapObject("Celestial Necklace of Bliss", 20000);
			yield return new MapObject("Crown of Dragontooth", 20000);
			yield return new MapObject("Dragon Scale Armor", 20000);
			yield return new MapObject("Endless Sack of Gold", 20000);
			yield return new MapObject("Helm of Heavenly Enlightenment", 20000);
			yield return new MapObject("Lion's Shield of Courage", 20000);
			yield return new MapObject("Orb of Vulnerability", 20000);
			yield return new MapObject("Orb of Inhibition", 20000);
			yield return new MapObject("Sandals of the Saint", 20000);
			yield return new MapObject("Sea Captain's Hat", 20000);
			yield return new MapObject("Sentinel's Shield", 20000);
			yield return new MapObject("Spellbinder's Hat", 20000);
			yield return new MapObject("Sword of Judgement", 20000);
			yield return new MapObject("Thunder Helmet", 20000);
			yield return new MapObject("Titan's Cuirass", 20000);
			yield return new MapObject("Titan's Gladius", 20000);
			yield return new MapObject("Tome of Air", 20000);
			yield return new MapObject("Tome of Earth", 20000);
			yield return new MapObject("Tome of Fire", 20000);
			yield return new MapObject("Tome of Water", 20000);
			yield return new MapObject("Vial of Dragon Blood", 20000);
			yield return new MapObject("Horn of the Abyss", 20000);
			yield return new MapObject("Admiral's Hat", 20000);
			yield return new MapObject("Angelic Alliance", 20000);
			yield return new MapObject("Armor of the Damned", 20000);
			yield return new MapObject("Bow of the Sharpshooter", 20000);
			yield return new MapObject("Cloak of the Undead King", 20000);
			yield return new MapObject("Cornucopia", 20000);
			yield return new MapObject("Elixir of Life", 20000);
			yield return new MapObject("Power of the Dragon Father", 20000);
			yield return new MapObject("Ring of the Magi", 20000);
			yield return new MapObject("Statue of Legion", 20000);
			yield return new MapObject("Titan's Thunder", 20000);
			yield return new MapObject("Wizard's Well", 20000);
			yield return new MapObject("Diplomat's Cloak", 20000);
			yield return new MapObject("Golden Goose", 20000);
			yield return new MapObject("Ironfist of the Ogre ", 20000);
			yield return new MapObject("Pendant of Reflection", 20000);
		}

		private static IEnumerable<DwellingMapObject> ListDwellings()
		{
			yield return new DwellingMapObject("Guardhouse (Pikeman)", MonsterFactory.GetMonster("Pikeman"));
			yield return new DwellingMapObject("Archers' Tower (Archer)", MonsterFactory.GetMonster("Archer"));
			yield return new DwellingMapObject("Griffin Tower (Griffint)", MonsterFactory.GetMonster("Griffin"));
			yield return new DwellingMapObject("Barracks (Swordsman)", MonsterFactory.GetMonster("Swordsman"));
			yield return new DwellingMapObject("Monastery (Monk)", MonsterFactory.GetMonster("Monk"));
			yield return new DwellingMapObject("Training Grounds (Cavalier)", MonsterFactory.GetMonster("Cavalier"));
			yield return new DwellingMapObject("Portal of Glory (Angel)", MonsterFactory.GetMonster("Angel"));
			yield return new DwellingMapObject("Centaur Stables (Centaur)", MonsterFactory.GetMonster("Centaur"));
			yield return new DwellingMapObject("Dwarf Cottage (Dwarf)", MonsterFactory.GetMonster("Dwarf"));
			yield return new DwellingMapObject("Homestead (Wood Elf)", MonsterFactory.GetMonster("Wood Elf"));
			yield return new DwellingMapObject("Enchanted Spring (Pegasus)", MonsterFactory.GetMonster("Pegasus"));
			yield return new DwellingMapObject("Dendroid Arches (Dendroid)", MonsterFactory.GetMonster("Dendroid Guard"));
			yield return new DwellingMapObject("Unicorn Glade (Unicorn)", MonsterFactory.GetMonster("Unicorn"));
			yield return new DwellingMapObject("Dragon Cliffs (Green Dragon)", MonsterFactory.GetMonster("Green Dragon"));
			yield return new DwellingMapObject("Workshop (Gremlin)", MonsterFactory.GetMonster("Gremlin"));
			yield return new DwellingMapObject("Parapet (Stone Gargoyle)", MonsterFactory.GetMonster("Stone Gargoyle"));
			//yield return new DwellingMapObject("Golem Factory (Golem) /2", MonsterFactory.GetMonster("Stone Golem"), MonsterFactory.GetMonster("Iron Golem"), MonsterFactory.GetMonster("Gold Golem"), MonsterFactory.GetMonster("Diamond Golem"));
			yield return new DwellingMapObject("Golem Factory (Golem)", MonsterFactory.GetMonster("Stone Golem"), MonsterFactory.GetMonster("Iron Golem"), MonsterFactory.GetMonster("Gold Golem"), MonsterFactory.GetMonster("Diamond Golem"));
			yield return new DwellingMapObject("Mage Tower (Mage)", MonsterFactory.GetMonster("Mage"));
			yield return new DwellingMapObject("Altar of Wishes (Genie)", MonsterFactory.GetMonster("Genie"));
			yield return new DwellingMapObject("Golden Pavilion (Naga)", MonsterFactory.GetMonster("Naga"));
			yield return new DwellingMapObject("Cloud Temple (Giant)", MonsterFactory.GetMonster("Giant"));
			yield return new DwellingMapObject("Imp Crucible (Imp)", MonsterFactory.GetMonster("Imp"));
			yield return new DwellingMapObject("Hall of Sins (Gog)", MonsterFactory.GetMonster("Gog"));
			yield return new DwellingMapObject("Kennels (Hell Hound)", MonsterFactory.GetMonster("Hell Hound"));
			yield return new DwellingMapObject("Demon Gate (Demon)", MonsterFactory.GetMonster("Demon"));
			yield return new DwellingMapObject("Hell Hole (Pit Fiend)", MonsterFactory.GetMonster("Pit Fiend"));
			yield return new DwellingMapObject("Fire Lake (Efreet)", MonsterFactory.GetMonster("Efreet"));
			yield return new DwellingMapObject("Forsaken Palace (Devil)", MonsterFactory.GetMonster("Devil"));
			yield return new DwellingMapObject("Cursed Temple (Skeleton)", MonsterFactory.GetMonster("Skeleton"));
			yield return new DwellingMapObject("Graveyard (Walking Dead)", MonsterFactory.GetMonster("Walking Dead"));
			yield return new DwellingMapObject("Tomb of Souls (Wight)", MonsterFactory.GetMonster("Wight"));
			yield return new DwellingMapObject("Estate (Vampire)", MonsterFactory.GetMonster("Vampire")) { ExtraMultiplier = 3 };
			yield return new DwellingMapObject("Mausoleum (Lich)", MonsterFactory.GetMonster("Lich"));
			yield return new DwellingMapObject("Hall of Darkness (Black Knight)", MonsterFactory.GetMonster("Black Knight"));
			yield return new DwellingMapObject("Dragon Vault (Bone Dragon)", MonsterFactory.GetMonster("Bone Dragon"));
			yield return new DwellingMapObject("Warren (Troglodyte)", MonsterFactory.GetMonster("Troglodyte"));
			yield return new DwellingMapObject("Harpy Loft (Harpy)", MonsterFactory.GetMonster("Harpy"));
			yield return new DwellingMapObject("Pillar of Eyes (Beholder)", MonsterFactory.GetMonster("Beholder"));
			yield return new DwellingMapObject("Chapel of Stilled Voices (Medusa)", MonsterFactory.GetMonster("Medusa"));
			yield return new DwellingMapObject("Labyrinth (Minotaur)", MonsterFactory.GetMonster("Minotaur"));
			yield return new DwellingMapObject("Manticore Lair (Manticore)", MonsterFactory.GetMonster("Manticore"));
			yield return new DwellingMapObject("Dragon Cave (Red Dragon)", MonsterFactory.GetMonster("Red Dragon"));
			yield return new DwellingMapObject("Goblin Barracks (Goblin)", MonsterFactory.GetMonster("Goblin"));
			yield return new DwellingMapObject("Wolf Pen (Wolf Rider)", MonsterFactory.GetMonster("Wolf Rider"));
			yield return new DwellingMapObject("Orc Tower (Orc)", MonsterFactory.GetMonster("Orc"));
			yield return new DwellingMapObject("Ogre Fort (Ogre)", MonsterFactory.GetMonster("Ogre"));
			yield return new DwellingMapObject("Cliff Nest (Roc)", MonsterFactory.GetMonster("Roc"));
			yield return new DwellingMapObject("Cyclops Cave (Cyclops)", MonsterFactory.GetMonster("Cyclops"));
			yield return new DwellingMapObject("Behemoth Crag (Behemoth)", MonsterFactory.GetMonster("Behemoth"));
			yield return new DwellingMapObject("Gnoll Hut (Gnoll)", MonsterFactory.GetMonster("Gnoll"));
			yield return new DwellingMapObject("Lizard Den (Lizardman)", MonsterFactory.GetMonster("Lizardman"));
			yield return new DwellingMapObject("Serpent Fly Hive (Serpent Fly)", MonsterFactory.GetMonster("Serpent Fly"));
			yield return new DwellingMapObject("Basilisk Pit (Basilisk)", MonsterFactory.GetMonster("Basilisk"));
			yield return new DwellingMapObject("Gorgon Lair (Gorgon)", MonsterFactory.GetMonster("Gorgon"));
			yield return new DwellingMapObject("Wyvern Nest (Wyvern)", MonsterFactory.GetMonster("Wyvern"));
			yield return new DwellingMapObject("Hydra Pond (Hydra)", MonsterFactory.GetMonster("Hydra"));
			yield return new DwellingMapObject("Magic Lantern (Pixie)", MonsterFactory.GetMonster("Pixie"));
			yield return new DwellingMapObject("Altar of Air (Air Elem.)", MonsterFactory.GetMonster("Air Elemental"));
			yield return new DwellingMapObject("Air Elemental Conflux (Air Elem.)", MonsterFactory.GetMonster("Air Elemental"));
			yield return new DwellingMapObject("Altar of Water (Water Elem.)", MonsterFactory.GetMonster("Water Elemental"));
			yield return new DwellingMapObject("Water Elemental Conflux (Water Elem.)", MonsterFactory.GetMonster("Water Elemental"));
			yield return new DwellingMapObject("Altar of Fire (Fire Elem.)", MonsterFactory.GetMonster("Fire Elemental"));
			yield return new DwellingMapObject("Fire Elemental Conflux (Fire Elem.)", MonsterFactory.GetMonster("Fire Elemental"));
			yield return new DwellingMapObject("Altar of Earth (Earth Elem.)", MonsterFactory.GetMonster("Earth Elemental"));
			yield return new DwellingMapObject("Earth Elemental Conflux (Earth Elem.)", MonsterFactory.GetMonster("Earth Elemental"));
			yield return new DwellingMapObject("Elemental Conflux (Multiple Elem.)", MonsterFactory.GetMonster("Air Elemental"), MonsterFactory.GetMonster("Water Elemental"), MonsterFactory.GetMonster("Fire Elemental"), MonsterFactory.GetMonster("Earth Elemental"));
			yield return new DwellingMapObject("Altar of Thought (Psychic Elem.)", MonsterFactory.GetMonster("Psychic Elemental"));
			yield return new DwellingMapObject("Pyre (Firebird)", MonsterFactory.GetMonster("Firebird"));
			yield return new DwellingMapObject("Nymph Waterfall (Nymph)", MonsterFactory.GetMonster("Nymph"));
			yield return new DwellingMapObject("Shack (Crew Mate)", MonsterFactory.GetMonster("Crew Mate"));
			yield return new DwellingMapObject("Frigate (Pirate)", MonsterFactory.GetMonster("Pirate"));
			yield return new DwellingMapObject("Nest (Stormbird)", MonsterFactory.GetMonster("Stormbird"));
			yield return new DwellingMapObject("Tower of the Seas (Sea Witch)", MonsterFactory.GetMonster("Sea Witch"));
			yield return new DwellingMapObject("Nix Fort (Nix)", MonsterFactory.GetMonster("Nix"));
			yield return new DwellingMapObject("Maelstrom (Sea Serpent)", MonsterFactory.GetMonster("Sea Serpent"));
			yield return new DwellingMapObject("Hovel (Peasant)", MonsterFactory.GetMonster("Peasant")) { ExtraMultiplier = 3 };
			yield return new DwellingMapObject("Thatched Hut (Halfling)", MonsterFactory.GetMonster("Halfling"));
			yield return new DwellingMapObject("Rogue Cavern (Rogue)", MonsterFactory.GetMonster("Rogue"));
			yield return new DwellingMapObject("Alehouse (Leprechaun)", MonsterFactory.GetMonster("Leprechaun"));
			yield return new DwellingMapObject("Boar Glen (Boar)", MonsterFactory.GetMonster("Boar"));
			yield return new DwellingMapObject("Nomad Tent (Nomad)", MonsterFactory.GetMonster("Nomad"));
			yield return new DwellingMapObject("Tomb of Curses (Mummy)", MonsterFactory.GetMonster("Mummy"));
			yield return new DwellingMapObject("Wineyard (Satyr)", MonsterFactory.GetMonster("Satyr"));
			yield return new DwellingMapObject("Treetop Tower (Sharpshooter)", MonsterFactory.GetMonster("Sharpshooter"));
			yield return new DwellingMapObject("Troll Bridge (Troll)", MonsterFactory.GetMonster("Troll"));
			yield return new DwellingMapObject("Ziggurat (Fangarm)", MonsterFactory.GetMonster("Fangarm"));
			yield return new DwellingMapObject("Enchanter's Hollow (Enchanter)", MonsterFactory.GetMonster("Enchanter"));
			yield return new DwellingMapObject("Magic Forest (Faerie Dragon)", MonsterFactory.GetMonster("Faerie Dragon"));
			yield return new DwellingMapObject("Sulfurous Lair (Rust Dragon)", MonsterFactory.GetMonster("Rust Dragon"));
			yield return new DwellingMapObject("Crystal Cave (Crystal Dragon)", MonsterFactory.GetMonster("Crystal Dragon"));
			yield return new DwellingMapObject("Frozen Cliffs (Azure Dragon)", MonsterFactory.GetMonster("Azure Dragon"));
		}
	}
}
